### ISSUE TITLE
hiera 2 and 3 compatibility

### ISSUE THREAD

**Issue by syntacticvexation** [voxpupuli/hiera-file#13] opened 2015-08-02 08:23 UTC
hiera-file doesn't currently work with hiera >= 2 (Puppet 4) when attempting to lookup files containing the . character.

This is because new versions of hiera use . to step into nested data structures.

More info here:
https://docs.puppetlabs.com/hiera/2.0/release_notes.html#new-feature-lookups-can-index-into-data-structures

https://tickets.puppetlabs.com/browse/HI-14

Thanks

**Comment by adrienthebo** [comment] 2015-12-07 20:41
Could you provide an example to reproduce this?

**Comment by syntacticvexation** [comment] 2015-12-11 01:51
A file without an extension will work fine like terminator_config, but a file such as test.png will not due to the aforementioned problem.

I did try to have a look at how to address the problem but I wasn't able to cover enough of the hiera internals to grasp what to do.  I couldn't figure out how to disable . as a character to step into data structures.  If there's no option to do that the plugin needs to provide a nested hash ie test.config.bak { test => config => bak } to address the issue.

**Comment by sergiik** [comment] 2016-02-11 15:22
I have faced the same issue with hiera-file (1.1.1) and hiera (3.0.6)
hiera.yaml I used: 
```
---
:backends:
  - yaml
  - file
:yaml:
  :datadir: /etc/puppetlabs/code/environments/production/hieradata
:file:
  :datadir: /etc/puppetlabs/code/environments/production/hieradata
  :interpolate: false
:hierarchy:
  - defaults
  - "%{clientcert}"
  - "%{environment}"
  - global
:merge_behaviour: deep
```

Then execute
`puppet  apply --verbose --debug -e '$somevar = hiera("test.txt") notify { $somevar: }'`

This generates error
`Error: Evaluation Error: Error while evaluating a Function Call, Could not find data item test.txt in any Hiera data file and no default supplied  at line`

But in fact **test.txt** file exists and available in : **/etc/puppetlabs/code/environments/production/hieradata/defaults.d/**
If I rename the file to **test** and try to get it with **hiera("test.txt")** it works just fine

**Comment by romracer** [comment] 2016-02-18 17:43
Same for me.  A very simple test case is a hiera.yaml with just the file backend and a datadir (default hierarchy of common is fine).  Then you can do something like this:

```
# hiera -c /root/hiera.yaml -d test1.txt
DEBUG: 2016-02-18 11:17:42 -0600: Hiera File backend starting
DEBUG: 2016-02-18 11:17:42 -0600: Using Hiera 1.x backend API to access instance of class Hiera::Backend::File_backend. Lookup recursion will not be detected
DEBUG: 2016-02-18 11:17:42 -0600: Looking up test1 in File backend
DEBUG: 2016-02-18 11:17:42 -0600: Hiera File_backend: looking for data source 'common'
nil
```

```
# hiera -c /root/hiera.yaml -d test1_txt
DEBUG: 2016-02-18 11:17:44 -0600: Hiera File backend starting
DEBUG: 2016-02-18 11:17:44 -0600: Using Hiera 1.x backend API to access instance of class Hiera::Backend::File_backend. Lookup recursion will not be detected
DEBUG: 2016-02-18 11:17:44 -0600: Looking up test1_txt in File backend
DEBUG: 2016-02-18 11:17:44 -0600: Hiera File_backend: looking for data source 'common'
Test file 1
```

From the output you can see the lookup in the first example is looking up `test1`.  I think this is due to the split() at line 252 [here](https://github.com/puppetlabs/hiera/blob/d12b1947f02069054c3ec4fb5eed54e36da79490/lib/hiera/backend.rb#L252).  I don't see any way to override that split, so I don't see any easy solution here.

Best workaround: don't use dot's in filenames you intend to access via the Hiera file backend if you're using Hiera 2 or 3.

**Comment by syntacticvexation** [comment] 2016-03-20 06:34
There's a new version of hiera out (3.1.0) that has a function that allows you to override the behaviour for keys with separators.  I've created a pull request that uses that function to allow filenames with extensions.  Let me know if it works for you.

**Comment by romracer** [comment] 2016-03-22 12:13
Is #17 still compatible with Hiera 1?  Looks like it upgrades the backend version, that would be the only thing I see.  But I think this is required since context is necessary for the fully qualified key.

I use PE so I can't test it locally (no Hiera 3.1.0 release yet) but it otherwise looks right to me.

**Comment by syntacticvexation** [comment] 2016-03-27 05:19
Yep, not sure, I've now updated my environment to use Puppet 4 and Hiera 3.  What about a Hiera 1 compat branch?

**Comment by dhollinger** [comment] 2019-02-27 20:20
Closing as we no longer support Hiera 1 or Hiera 2

**Closed by dhollinger** 2019-02-27 20:20 UTC
